# -*- coding: utf-8 -*-
"""由 lexicon.json（PDF 解析 + 校對後的權威字庫）產生「場景練習單元」。

每個單元照 wordmomo 的循序漸進結構，從單字一路build到整句：

  step 1  單字    目標字，中文釋義直接取自 PDF
  step 2  單字    同一句裡的另一個字，中文釋義同樣取自 PDF
  step 3  詞組    該句中出現的固定搭配（優先），中文取自 PHRASES 對照表
  step 4  整句    PDF 的完整例句 + 官方中文翻譯

輸出 data/banks.js，供前端直接載入。
"""
import json
import re
from pathlib import Path

from scenarios import SCENARIOS, norm

ROOT = Path(__file__).resolve().parent.parent
LEX = ROOT / "tools" / "lexicon.json"
OUT = ROOT / "data" / "banks.js"
REPORT = ROOT / "tools" / "bank_report.txt"

# 固定搭配：片語 -> (中文, 適用場景)。優先挑「例句裡真的會出現」的片語。
PHRASES = {
    # food
    "birthday cake": ("生日蛋糕", "food"),
    "fresh fruit tea": ("新鮮水果茶", "food"),
    "fruit tea": ("水果茶", "food"),
    "a cup of tea": ("一杯茶", "food"),
    "a bowl of rice": ("一碗飯", "food"),
    "French fries": ("薯條", "food"),
    "hot dog": ("熱狗", "food"),
    "ice cream": ("冰淇淋", "food"),
    "fast food": ("速食", "food"),
    "cold drink": ("冷飲", "food"),
    "a cup of coffee": ("一杯咖啡", "food"),
    "green tea": ("綠茶", "food"),
    "a big lunch": ("一頓大午餐", "food"),
    "sweet tooth": ("甜食牙", "food"),
    # school
    "go to school": ("去上學", "school"),
    "junior high school": ("國中", "school"),
    "senior high school": ("高中", "school"),
    "elementary school": ("小學", "school"),
    "English class": ("英文課", "school"),
    "PE class": ("體育課", "school"),
    "take notes": ("記筆記", "school"),
    "do homework": ("做作業", "school"),
    "good grades": ("好成績", "school"),
    "math quiz": ("數學小考", "school"),
    "the blackboard": ("黑板", "school"),
    "in class": ("在課堂上", "school"),
    # home
    "my bedroom": ("我的臥室", "home"),
    "the living room": ("客廳", "home"),
    "in the kitchen": ("在廚房裡", "home"),
    "on the bed": ("在床上", "home"),
    "clean the floor": ("打掃地板", "home"),
    "take a bath": ("洗澡", "home"),
    "watch TV": ("看電視", "home"),
    "in the bathroom": ("在浴室裡", "home"),
    # animal
    "a pet dog": ("寵物狗", "animal"),
    "zoo animals": ("動物園的動物", "animal"),
    "a sad animal": ("可憐的動物", "animal"),
    "farm animals": ("農場動物", "animal"),
    "sea animals": ("海洋動物", "animal"),
    # nature
    "in the garden": ("在花園裡", "nature"),
    "green leaves": ("綠色的葉子", "nature"),
    "a big tree": ("一棵大樹", "nature"),
    "the blue sky": ("藍色的天空", "nature"),
    "mountain climbing": ("登山", "nature"),
    # weather
    "rainy day": ("雨天", "weather"),
    "snowy day": ("下雪天", "weather"),
    "windy day": ("刮風的日子", "weather"),
    "hot weather": ("炎熱的天氣", "weather"),
    "cold weather": ("寒冷的天氣", "weather"),
    "four seasons": ("四季", "weather"),
    # time
    "every morning": ("每天早上", "time"),
    "last night": ("昨晚", "time"),
    "next week": ("下週", "time"),
    "this year": ("今年", "time"),
    "a long time": ("很長時間", "time"),
    "every day": ("每天", "time"),
    "all day": ("整天", "time"),
    # body
    "sore throat": ("喉嚨痛", "body"),
    "a sore throat": ("喉嚨痛", "body"),
    "a headache": ("頭痛", "body"),
    "good health": ("良好的健康", "body"),
    "lose weight": ("減重", "body"),
    "hurt my knee": ("傷到我的膝蓋", "body"),
    # clothes
    "a pair of shoes": ("一雙鞋", "clothes"),
    "school uniform": ("校服", "clothes"),
    "a pink skirt": ("一件粉紅色的裙子", "clothes"),
    "wear a hat": ("戴帽子", "clothes"),
    # travel
    "go abroad": ("出國", "travel"),
    "by train": ("搭火車", "travel"),
    "by bus": ("搭公車", "travel"),
    "on foot": ("步行", "travel"),
    "take a bus": ("搭公車", "travel"),
    "ride a bike": ("騎腳踏車", "travel"),
    "MRT station": ("捷運站", "travel"),
    "buy a ticket": ("買一張票", "travel"),
    "a long trip": ("長途旅行", "travel"),
    # city
    "the train station": ("火車站", "city"),
    "post office": ("郵局", "city"),
    "book store": ("書店", "city"),
    "in the city": ("在城市裡", "city"),
    "the city center": ("市中心", "city"),
    # money
    "a lot of money": ("很多錢", "money"),
    "pocket money": ("零用錢", "money"),
    "the right size": ("剛好的尺寸", "money"),
    "spend money": ("花錢", "money"),
    "buy and sell": ("買與賣", "money"),
    "on sale": ("特價中", "money"),
    # work
    "a new job": ("一份新工作", "work"),
    "go to work": ("去上班", "work"),
    "a hard-working person": ("勤勞的人", "work"),
    "my boss": ("我的老闆", "work"),
    "a big company": ("大公司", "work"),
    # sport
    "play football": ("踢足球", "sport"),
    "play basketball": ("打籃球", "sport"),
    "a football game": ("一場足球賽", "sport"),
    "play tennis": ("打網球", "sport"),
    "Sports Day": ("運動會", "sport"),
    "play with friends": ("和朋友一起玩", "sport"),
    "on the playground": ("在操場上", "sport"),
    "go jogging": ("去慢跑", "sport"),
    # festival
    "Christmas present": ("聖誕節禮物", "festival"),
    "New Year's Eve": ("除夕夜", "festival"),
    "birthday party": ("生日派對", "festival"),
    "a movie ticket": ("一張電影票", "festival"),
    "watch a movie": ("看電影", "festival"),
    "play the piano": ("彈鋼琴", "festival"),
    # feeling
    "be happy": ("很高興", "feeling"),
    "be afraid": ("害怕", "feeling"),
    "feel sad": ("感到難過", "feeling"),
    "be glad": ("感到高興", "feeling"),
    "a good time": ("一段好時光", "feeling"),
    "be proud of": ("為…感到驕傲", "feeling"),
    "be angry at": ("對…生氣", "feeling"),
    # action
    "do homework": ("做作業", "action"),
    "go to bed": ("上床睡覺", "action"),
    "get up": ("起床", "action"),
    "look at": ("看著", "action"),
    "listen to": ("聽", "action"),
    "take care": ("保重", "action"),
    "wait for": ("等待", "action"),
    "help me": ("幫我", "action"),
    "come back": ("回來", "action"),
    "clean up": ("收拾乾淨", "action"),
    "turn on": ("打開", "action"),
    "turn off": ("關掉", "action"),
    # describe
    "a big house": ("一間大房子", "describe"),
    "a long time": ("很長時間", "describe"),
    "very good": ("非常好", "describe"),
    "too hot": ("太熱", "describe"),
    "very interesting": ("非常有趣", "describe"),
    "a good student": ("好學生", "describe"),
    "old and young": ("老與少", "describe"),
    # talk
    "thank you": ("謝謝", "talk"),
    "good morning": ("早安", "talk"),
    "good night": ("晚安", "talk"),
    "see you later": ("待會見", "talk"),
    "how are you": ("你好嗎", "talk"),
    "excuse me": ("不好意思", "talk"),
    "you're welcome": ("不客氣", "talk"),
    "take care": ("保重", "talk"),
    # family
    "my mother": ("我的媽媽", "family"),
    "my father": ("我的爸爸", "family"),
    "my parents": ("我的父母", "family"),
    "an older sister": ("姊姊", "family"),
    "my cousin": ("我的表姊", "family"),
    "a big family": ("大家庭", "family"),
    # basic
    "a lot of": ("很多", "basic"),
    "a few": ("一些", "basic"),
    "a little": ("一點", "basic"),
    "every day": ("每天", "basic"),
    "of course": ("當然", "basic"),
    "at home": ("在家", "basic"),
    "in the morning": ("在早上", "basic"),
    "at night": ("在晚上", "basic"),
    "thank you": ("謝謝", "basic"),
}

# 第二批：依 tools/need_phrase.txt 的缺口補齊。
# 規則一樣——片語的最後一個字要是目標單字，中文必須是讀得通的中文。
PHRASES.update({
    # ---- basic ----
    "one of": ("…其中之一", "basic"),
    "each of": ("每一個", "basic"),
    "most of": ("大部分", "basic"),
    "all of": ("全部", "basic"),
    "kind of": ("一種", "basic"),
    "instead of": ("而不是", "basic"),
    "because of": ("因為", "basic"),
    "out of": ("從…外面", "basic"),
    "in front of": ("在…前面", "basic"),
    "such as": ("例如", "basic"),
    "as far as": ("就…而言", "basic"),
    "as well as": ("以及", "basic"),
    "what if": ("如果…怎麼辦", "basic"),
    "even if": ("即使", "basic"),
    "as if": ("彷彿", "basic"),
    "in case": ("以防萬一", "basic"),
    "something else": ("別的東西", "basic"),
    "someone else": ("別的人", "basic"),
    "anywhere else": ("其他任何地方", "basic"),
    "everyone else": ("其他每個人", "basic"),
    "the same": ("一樣的", "basic"),
    "at the same time": ("同時", "basic"),
    "all the same": ("完全一樣", "basic"),
    "even more": ("更多", "basic"),
    "nothing to": ("沒有東西可以", "basic"),
    "plenty of": ("大量的", "basic"),
    "a bit of": ("一點點", "basic"),
    "the same as": ("和…一樣", "basic"),
    "should be": ("應該是", "basic"),
    "would be": ("會是", "basic"),
    "could be": ("可能是", "basic"),
    "must be": ("一定是", "basic"),
    "there is": ("有", "basic"),
    "here is": ("這是", "basic"),
    "that is": ("那就是", "basic"),
    "this is": ("這是", "basic"),
    "it is": ("它是", "basic"),
    "he is": ("他是", "basic"),
    "she is": ("她是", "basic"),
    "i am": ("我是", "basic"),
    "they are": ("他們是", "basic"),
    "you are": ("你是", "basic"),
    "we are": ("我們是", "basic"),
    "do not": ("不要", "basic"),
    "does not": ("不", "basic"),
    "did not": ("沒有", "basic"),
    "be good at": ("擅長", "basic"),
    "be interested in": ("對…感興趣", "basic"),
    "be full of": ("充滿", "basic"),
    "be famous for": ("以…聞名", "basic"),
    "be different": ("不一樣", "basic"),
    "be afraid of": ("害怕", "basic"),
    "be ready": ("準備好", "basic"),
    "be able to": ("能夠", "basic"),
    "be kind to": ("對…友善", "basic"),
    "be late": ("遲到", "basic"),
    "be early": ("早到", "basic"),
    "be busy": ("很忙", "basic"),
    "be quiet": ("安靜", "basic"),
    "be hungry": ("肚子餓", "basic"),
    "be thirsty": ("口渴", "basic"),
    "be tired": ("疲倦", "basic"),
    "be free": ("有空閒", "basic"),
    "be right": ("正確", "basic"),
    "be sure": ("確定", "basic"),
    "be angry": ("生氣", "basic"),
    "be honest": ("誠實", "basic"),
    "be polite": ("有禮貌", "basic"),
    "be careful": ("小心", "basic"),
    "be brave": ("勇敢", "basic"),
    "be honest with": ("對…誠實", "basic"),
    "in fact": ("事實上", "basic"),
    "of course": ("當然", "basic"),
    "at least": ("至少", "basic"),
    "at once": ("立刻", "basic"),
    "at first": ("起初", "basic"),
    "in common": ("共同的", "basic"),
    # ---- food ----
    "fresh fruit": ("新鮮水果", "food"),
    "a piece of cake": ("很容易的事", "food"),
    "a glass of": ("一杯", "food"),
    "a bowl of": ("一碗", "food"),
    "a cup of": ("一杯", "food"),
    "hot coffee": ("熱咖啡", "food"),
    "a hot dog": ("熱狗", "food"),
    "green salad": ("生菜沙拉", "food"),
    "fresh meat": ("新鮮的肉", "food"),
    "fried egg": ("荷包蛋", "food"),
    "cold water": ("冷水", "food"),
    "clean water": ("乾淨的水", "food"),
    "sugar in": ("加糖在", "food"),
    "a sweet": ("一顆糖", "food"),
    "very sweet": ("很甜", "food"),
    "eat well": ("吃得好", "food"),
    "eat more": ("多吃一點", "food"),
    "cook a meal": ("做一頓飯", "food"),
    "make dinner": ("做晚餐", "food"),
    "order food": ("點餐", "food"),
    "a good restaurant": ("一家好餐廳", "food"),
    "fresh vegetables": ("新鮮蔬菜", "food"),
    "a banana": ("一根香蕉", "food"),
    "a watermelon": ("一顆西瓜", "food"),
    "a cookie": ("一塊餅乾", "food"),
    "a piece of bread": ("一塊麵包", "food"),
    "orange juice": ("柳橙汁", "food"),
    "apple juice": ("蘋果汁", "food"),
    "milk tea": ("奶茶", "food"),
    "a straw": ("一根吸管", "food"),
    "a menu": ("一份菜單", "food"),
    "a meal": ("一餐", "food"),
    "a waiter": ("一位服務生", "food"),
    "a waitress": ("一位女服務生", "food"),
    "delicious food": ("美味的食物", "food"),
    "fresh air": ("新鮮空氣", "food"),
    "a bakery": ("一家麵包店", "food"),
    "boil water": ("煮開水", "food"),
    "bake a cake": ("烤一個蛋糕", "food"),
    "fry an egg": ("煎一個蛋", "food"),
    "a vegetable": ("一種蔬菜", "food"),
    "a bean": ("一顆豆子", "food"),
    "a dumpling": ("一個水餃", "food"),
    "a pizza": ("一個披薩", "food"),
    "a steak": ("一份牛排", "food"),
    "a snack": ("一份點心", "food"),
    "a treat": ("一份小點心", "food"),
    "a salt": ("一種鹽", "food"),
    "a butter": ("一塊奶油", "food"),
    "a candy": ("一顆糖", "food"),
    "a meat": ("一種肉", "food"),
    "a honey": ("一份蜂蜜", "food"),
    "a milk": ("一杯牛奶", "food"),
    "a cola": ("一杯可樂", "food"),
    "a juice": ("一杯果汁", "food"),
    "a hamburger": ("一個漢堡", "food"),
    "a toast": ("一片吐司", "food"),
    "a chocolate": ("一塊巧克力", "food"),
    "a popcorn": ("一份爆米花", "food"),
    "a spaghetti": ("一份義大利麵", "food"),
    "a lettuce": ("一株萵苣", "food"),
    "a lemon": ("一顆檸檬", "food"),
    "a peach": ("一顆桃子", "food"),
    "a pear": ("一顆梨子", "food"),
    "a grape": ("一顆葡萄", "food"),
    "a turkey": ("一隻火雞", "food"),
    "hot tea": ("熱茶", "food"),
    "cold water": ("冷水", "food"),
    # ---- time ----
    "a birthday": ("一個生日", "time"),
    "a holiday": ("一個假日", "time"),
    "an hour": ("一個小時", "time"),
    "a minute": ("一分鐘", "time"),
    "a quarter": ("一刻鐘", "time"),
    "a second": ("一秒", "time"),
    "monday": ("星期一", "time"),
    "friday": ("星期五", "time"),
    "saturday": ("星期六", "time"),
    "january": ("一月", "time"),
    "february": ("二月", "time"),
    "march": ("三月", "time"),
    "april": ("四月", "time"),
    "may": ("五月", "time"),
    "june": ("六月", "time"),
    "july": ("七月", "time"),
    "august": ("八月", "time"),
    "september": ("九月", "time"),
    "october": ("十月", "time"),
    "november": ("十一月", "time"),
    "december": ("十二月", "time"),
    "noon": ("中午", "time"),
    "midnight": ("午夜", "time"),
    "at noon": ("在中午", "time"),
    "once a week": ("一週一次", "time"),
    "twice a month": ("一個月兩次", "time"),
    "three times": ("三次", "time"),
    "a long time": ("很長時間", "time"),
    "in the past": ("在過去", "time"),
    "in the future": ("在未來", "time"),
    "from now on": ("從現在起", "time"),
    "any day": ("任何一天", "time"),
    "one day": ("有一天", "time"),
    "the other day": ("前幾天", "time"),
    "day by day": ("一天一天地", "time"),
    "all day": ("一整天", "time"),
    "last year": ("去年", "time"),
    "next year": ("明年", "time"),
    "last month": ("上個月", "time"),
    "next month": ("下個月", "time"),
    "a date": ("一個日期", "time"),
    "what date": ("幾號", "time"),
    "one": ("一", "time"),
    "two": ("二", "time"),
    "three": ("三", "time"),
    "four": ("四", "time"),
    "five": ("五", "time"),
    "six": ("六", "time"),
    "seven": ("七", "time"),
    "eight": ("八", "time"),
    "nine": ("九", "time"),
    "ten": ("十", "time"),
    "fourteen": ("十四", "time"),
    "fifteen": ("十五", "time"),
    "sixteen": ("十六", "time"),
    "seventeen": ("十七", "time"),
    "eighteen": ("十八", "time"),
    "nineteen": ("十九", "time"),
    "twenty": ("二十", "time"),
    "thirty": ("三十", "time"),
    "forty": ("四十", "time"),
    "fifty": ("五十", "time"),
    "sixty": ("六十", "time"),
    "seventy": ("七十", "time"),
    "eighty": ("八十", "time"),
    "ninety": ("九十", "time"),
    "zero": ("零", "time"),
    "the first": ("第一", "time"),
    "the second": ("第二", "time"),
    "the third": ("第三", "time"),
    # ---- action ----
    "go to": ("去", "action"),
    "go back": ("回去", "action"),
    "go out": ("出門", "action"),
    "go home": ("回家", "action"),
    "go up": ("上去", "action"),
    "go down": ("下去", "action"),
    "go away": ("走開", "action"),
    "go on": ("繼續", "action"),
    "go over": ("過去看看", "action"),
    "look for": ("尋找", "action"),
    "look out": ("小心", "action"),
    "look after": ("照顧", "action"),
    "think of": ("想到", "action"),
    "think about": ("想著", "action"),
    "take care of": ("照顧", "action"),
    "take a rest": ("休息一下", "action"),
    "take part": ("參加", "action"),
    "take turns": ("輪流", "action"),
    "give up": ("放棄", "action"),
    "find out": ("查明", "action"),
    "find a": ("找到一個", "action"),
    "ask for": ("要求", "action"),
    "ask about": ("詢問", "action"),
    "want to": ("想要", "action"),
    "need to": ("需要", "action"),
    "try to": ("試著", "action"),
    "try hard": ("努力", "action"),
    "keep going": ("繼續走", "action"),
    "keep clean": ("保持清潔", "action"),
    "move to": ("搬到", "action"),
    "move on": ("繼續前進", "action"),
    "set up": ("設置", "action"),
    "set the": ("設定那個", "action"),
    "hold a": ("拿著一個", "action"),
    "hold on": ("等一下", "action"),
    "carry a": ("提著一個", "action"),
    "dig in": ("挖進去", "action"),
    "join in": ("參加", "action"),
    "pick up": ("撿起", "action"),
    "point at": ("指向", "action"),
    "point to": ("指著", "action"),
    "wave at": ("向…揮手", "action"),
    "nod at": ("對…點頭", "action"),
    "bow to": ("向…鞠躬", "action"),
    "hang up": ("掛上", "action"),
    "touch the": ("觸碰那個", "action"),
    "kill a": ("殺死一隻", "action"),
    "burn a": ("燒毀一個", "action"),
    "begin to": ("開始", "action"),
    "build a": ("建造一個", "action"),
    "check the": ("檢查那個", "action"),
    "choose a": ("選擇一個", "action"),
    "collect a": ("收集一個", "action"),
    "cover a": ("蓋住一個", "action"),
    "drop a": ("掉落一個", "action"),
    "forget to": ("忘了要", "action"),
    "guess a": ("猜一個", "action"),
    "heat the": ("加熱那個", "action"),
    "hurry up": ("趕快", "action"),
    "knock on": ("敲打", "action"),
    "send a": ("寄一個", "action"),
    "tell the": ("告訴那個", "action"),
    "learn to": ("學會", "action"),
    "learn a": ("學會一個", "action"),
    "practise a": ("練習一個", "action"),
    "do homework": ("做作業", "action"),
    "do the dishes": ("洗碗", "action"),
    "take a photo": ("拍一張照片", "action"),
    "take a bus": ("搭公車", "action"),
    "wake up": ("醒來", "action"),
    "wait for": ("等待", "action"),
    "get up": ("起床", "action"),
    "get on": ("搭上", "action"),
    "get off": ("下車", "action"),
    "get ready": ("準備好", "action"),
    "turn on": ("打開", "action"),
    "turn off": ("關掉", "action"),
    "turn left": ("向左轉", "action"),
    "turn right": ("向右轉", "action"),
    "sit down": ("坐下", "action"),
    "stand up": ("站起來", "action"),
    "clean up": ("收拾乾淨", "action"),
    "try on": ("試穿", "action"),
    "write down": ("寫下來", "action"),
    "read a book": ("讀一本書", "action"),
    "sing a song": ("唱一首歌", "action"),
    "play with": ("和…一起玩", "action"),
    "swim in": ("在…游泳", "action"),
    "climb a": ("攀爬一個", "action"),
    "open the door": ("開門", "action"),
    "close the door": ("關門", "action"),
    "use a": ("使用一個", "action"),
    "buy some": ("買一些", "action"),
    "make a": ("製作一個", "action"),
    "help with": ("幫忙處理", "action"),
    "look like": ("看起來像", "action"),
    "act like": ("表現得像", "action"),
    # ---- school ----
    "a book": ("一本書", "school"),
    "a pen": ("一支筆", "school"),
    "a pencil": ("一支鉛筆", "school"),
    "a bell": ("一個鈴", "school"),
    "a classroom": ("一間教室", "school"),
    "a classmate": ("一位同學", "school"),
    "an answer": ("一個答案", "school"),
    "a question": ("一個問題", "school"),
    "a word": ("一個字", "school"),
    "a sentence": ("一個句子", "school"),
    "a lesson": ("一課", "school"),
    "a list": ("一份清單", "school"),
    "a mistake": ("一個錯誤", "school"),
    "a rule": ("一條規則", "school"),
    "a team": ("一個團隊", "school"),
    "a group": ("一組", "school"),
    "a page": ("一頁", "school"),
    "a part": ("一部分", "school"),
    "a test": ("一場考試", "school"),
    "a quiz": ("一次小考", "school"),
    "a student": ("一位學生", "school"),
    "a teacher": ("一位老師", "school"),
    "english class": ("英文課", "school"),
    "math class": ("數學課", "school"),
    "music class": ("音樂課", "school"),
    "art class": ("美術課", "school"),
    "after class": ("課後", "school"),
    "in class": ("在課堂上", "school"),
    "at school": ("在學校", "school"),
    "go to school": ("去上學", "school"),
    "come to school": ("來上學", "school"),
    "copy the": ("抄下那個", "school"),
    "mark the": ("標記那個", "school"),
    "spell a": ("拼出", "school"),
    "prepare for": ("為…做準備", "school"),
    "study hard": ("努力用功", "school"),
    "study english": ("學英文", "school"),
    "pass the": ("通過那個", "school"),
    "fail the": ("沒通過那個", "school"),
    "ask a question": ("問一個問題", "school"),
    "answer a question": ("回答問題", "school"),
    "take notes": ("記筆記", "school"),
    "do homework": ("做作業", "school"),
    "a blackboard": ("一塊黑板", "school"),
    "a playground": ("一個操場", "school"),
    "a screen": ("一個螢幕", "school"),
    "a book store": ("一家書店", "school"),
    "a comic": ("一本漫畫", "school"),
    "on the playground": ("在操場上", "school"),
    "in the classroom": ("在教室裡", "school"),
    "be smart": ("很聰明", "school"),
    "be polite to": ("對…有禮貌", "school"),
    "be proud of": ("為…感到驕傲", "school"),
    # ---- describe ----
    "a big": ("一個大的", "describe"),
    "a small": ("一個小的", "describe"),
    "a long": ("一個長的", "describe"),
    "a short": ("一個短的", "describe"),
    "a high": ("一個高的", "describe"),
    "a red": ("一個紅色的", "describe"),
    "a yellow": ("一個黃色的", "describe"),
    "a brown": ("一個褐色的", "describe"),
    "a sharp": ("一把尖銳的", "describe"),
    "a slow": ("一個慢的", "describe"),
    "a giant": ("一個巨大的", "describe"),
    "a dark": ("一個黑暗的", "describe"),
    "a clear": ("一個清澈的", "describe"),
    "a circle": ("一個圓圈", "describe"),
    "a poor": ("一個窮的", "describe"),
    "a rich": ("一個富有的", "describe"),
    "a simple": ("一個簡單的", "describe"),
    "a popular": ("一個受歡迎的", "describe"),
    "a terrible": ("一個糟糕的", "describe"),
    "a wonderful": ("一個很棒的", "describe"),
    "a bright": ("一個明亮的", "describe"),
    "a careful": ("一個小心的", "describe"),
    "a common": ("一個常見的", "describe"),
    "a quick": ("一個快的", "describe"),
    "a safe": ("一個安全的", "describe"),
    "a straight": ("一條直的", "describe"),
    "a stupid": ("一件愚蠢的", "describe"),
    "a dangerous": ("一個危險的", "describe"),
    "a different": ("一個不同的", "describe"),
    "a difficult": ("一個困難的", "describe"),
    "an excellent": ("一個傑出的", "describe"),
    "a dot": ("一個點", "describe"),
    "a free": ("一個自由的", "describe"),
    "a real": ("一個真實的", "describe"),
    "a wise": ("一個明智的", "describe"),
    "a convenient": ("一個方便的", "describe"),
    "very big": ("非常大", "describe"),
    "very small": ("非常小", "describe"),
    "very good": ("非常好", "describe"),
    "very hot": ("非常熱", "describe"),
    "very cold": ("非常冷", "describe"),
    "very quiet": ("非常安靜", "describe"),
    "very bright": ("非常明亮", "describe"),
    "very slow": ("非常慢", "describe"),
    "too big": ("太大", "describe"),
    "too small": ("太小", "describe"),
    "too hot": ("太熱", "describe"),
    "too long": ("太長", "describe"),
    "too heavy": ("太重", "describe"),
    "too much": ("太多", "describe"),
    "too many": ("太多", "describe"),
    "really good": ("真的好", "describe"),
    "really bad": ("真的很糟", "describe"),
    "really different": ("真的很不一樣", "describe"),
    "quite good": ("相當不錯", "describe"),
    "quite different": ("相當不同", "describe"),
    # ---- feeling ----
    "a happy": ("一個快樂的", "feeling"),
    "a sad": ("一個難過的", "feeling"),
    "a funny": ("一個好笑的", "feeling"),
    "a nice": ("一個好的", "feeling"),
    "a kind": ("一個善良的", "feeling"),
    "a shy": ("一個害羞的", "feeling"),
    "a dream": ("一個夢想", "feeling"),
    "a surprise": ("一個驚喜", "feeling"),
    "a trouble": ("一個麻煩", "feeling"),
    "a problem": ("一個問題", "feeling"),
    "a dream": ("一個夢", "feeling"),
    "a joy": ("一份喜悅", "feeling"),
    "life": ("人生", "feeling"),
    "laugh at": ("嘲笑", "feeling"),
    "hope for": ("希望", "feeling"),
    "worry about": ("擔心", "feeling"),
    "cheer up": ("打起精神", "feeling"),
    "care about": ("關心", "feeling"),
    "miss you": ("想你", "feeling"),
    "believe in": ("相信", "feeling"),
    "feel happy": ("感到開心", "feeling"),
    "feel sad": ("感到難過", "feeling"),
    "feel tired": ("感到疲累", "feeling"),
    "be honest": ("誠實", "feeling"),
    "be friendly": ("友善", "feeling"),
    "be excited": ("很興奮", "feeling"),
    "be excited about": ("對…感到興奮", "feeling"),
    "be excited to": ("興奮地要", "feeling"),
    "be surprised": ("感到驚訝", "feeling"),
    "be interested": ("感興趣", "feeling"),
    "be interesting": ("有趣", "feeling"),
    "be boring": ("令人無聊", "feeling"),
    "be bored": ("感到無聊", "feeling"),
    "be crazy": ("瘋狂", "feeling"),
    "be strange": ("奇怪", "feeling"),
    "be serious": ("認真", "feeling"),
    "be scared": ("害怕", "feeling"),
    "be happy about": ("為…感到高興", "feeling"),
    "be glad to": ("樂於", "feeling"),
    "enjoy": ("享受", "feeling"),
    "a stranger": ("一個陌生人", "feeling"),
    "a hobby": ("一個嗜好", "feeling"),
    "a habit": ("一個習慣", "feeling"),
    "a favorite": ("最喜愛的", "feeling"),
    "an idea": ("一個點子", "feeling"),
    # ---- home ----
    "a cup": ("一個杯子", "home"),
    "a pot": ("一個鍋子", "home"),
    "a bowl": ("一個碗", "home"),
    "a lid": ("一個蓋子", "home"),
    "a ring": ("一枚戒指", "home"),
    "a seat": ("一個座位", "home"),
    "a toy": ("一個玩具", "home"),
    "a tub": ("一個浴缸", "home"),
    "a lamp": ("一盞檯燈", "home"),
    "a mat": ("一個墊子", "home"),
    "a bottle": ("一個瓶子", "home"),
    "a basket": ("一個籃子", "home"),
    "a rope": ("一條繩子", "home"),
    "a tool": ("一個工具", "home"),
    "a knife": ("一把刀", "home"),
    "a couch": ("一張沙發", "home"),
    "a blanket": ("一條毯子", "home"),
    "a drawer": ("一個抽屜", "home"),
    "a corner": ("一個角落", "home"),
    "a balcony": ("一個陽台", "home"),
    "a yard": ("一個庭院", "home"),
    "a gate": ("一道大門", "home"),
    "a pocket": ("一個口袋", "home"),
    "a machine": ("一台機器", "home"),
    "a garbage": ("一袋垃圾", "home"),
    "at home": ("在家", "home"),
    "in the living room": ("在客廳裡", "home"),
    "in the kitchen": ("在廚房裡", "home"),
    "in my bedroom": ("在我的臥室裡", "home"),
    "in the bathroom": ("在浴室裡", "home"),
    "on the bed": ("在床上", "home"),
    "on the table": ("在桌上", "home"),
    "under the bed": ("在床底下", "home"),
    "next to": ("緊鄰", "home"),
    "make the bed": ("整理床鋪", "home"),
    "clean the room": ("打掃房間", "home"),
    "sweep the floor": ("掃地", "home"),
    "do the dishes": ("洗碗", "home"),
    "take out the garbage": ("倒垃圾", "home"),
    "turn on the light": ("開燈", "home"),
    "turn off the light": ("關燈", "home"),
    "watch tv": ("看電視", "home"),
    "a comfortable": ("一把舒適的", "home"),
    "a noisy": ("一個吵雜的", "home"),
    "a muddy": ("一個泥濘的", "home"),
    "a dirty": ("一件髒的", "home"),
    "a tidy": ("一個整齊的", "home"),
    # ---- city ----
    "a bank": ("一家銀行", "city"),
    "a zoo": ("一座動物園", "city"),
    "a bookstore": ("一家書店", "city"),
    "a theater": ("一家電影院", "city"),
    "a hotel": ("一間旅館", "city"),
    "a church": ("一座教堂", "city"),
    "a temple": ("一座寺廟", "city"),
    "a castle": ("一座城堡", "city"),
    "a farm": ("一個農場", "city"),
    "a factory": ("一間工廠", "city"),
    "a town": ("一個小鎮", "city"),
    "a country": ("一個國家", "city"),
    "a city": ("一座城市", "city"),
    "the world": ("世界", "city"),
    "a sign": ("一個標示", "city"),
    "a bench": ("一張長椅", "city"),
    "a letter": ("一封信", "city"),
    "a stamp": ("一張郵票", "city"),
    "an envelope": ("一個信封", "city"),
    "a postcard": ("一張明信片", "city"),
    "an e-mail": ("一封電子郵件", "city"),
    "the internet": ("網路", "city"),
    "a newspaper": ("一份報紙", "city"),
    "the news": ("新聞", "city"),
    "a supermarket": ("一家超市", "city"),
    "a department store": ("一家百貨公司", "city"),
    "a book store": ("一家書店", "city"),
    "the post office": ("郵局", "city"),
    "a square": ("一個廣場", "city"),
    "a block": ("一個街區", "city"),
    "the sidewalk": ("人行道", "city"),
    "a police": ("一位警察", "city"),
    "the middle": ("中間", "city"),
    "a mailman": ("一位郵差", "city"),
    "in public": ("在公開場合", "city"),
    "go shopping": ("去購物", "city"),
    "live in": ("住在", "city"),
    "walk around": ("到處走", "city"),
    "inside the": ("在…裡面", "city"),
    "outside the": ("在…外面", "city"),
    # ---- animal ----
    "a cat": ("一隻貓", "animal"),
    "a dog": ("一隻狗", "animal"),
    "a bird": ("一隻鳥", "animal"),
    "a fish": ("一條魚", "animal"),
    "an ant": ("一隻螞蟻", "animal"),
    "a bee": ("一隻蜜蜂", "animal"),
    "a bug": ("一隻蟲子", "animal"),
    "a cow": ("一頭牛", "animal"),
    "a fox": ("一隻狐狸", "animal"),
    "a frog": ("一隻青蛙", "animal"),
    "a hen": ("一隻母雞", "animal"),
    "a horse": ("一匹馬", "animal"),
    "a lion": ("一隻獅子", "animal"),
    "a whale": ("一頭鯨魚", "animal"),
    "a zebra": ("一匹斑馬", "animal"),
    "a duck": ("一隻鴨子", "animal"),
    "a goat": ("一隻山羊", "animal"),
    "a sheep": ("一隻羊", "animal"),
    "an elephant": ("一頭大象", "animal"),
    "a hippo": ("一隻河馬", "animal"),
    "a rabbit": ("一隻兔子", "animal"),
    "a puppy": ("一隻小狗", "animal"),
    "a shark": ("一條鯊魚", "animal"),
    "an insect": ("一隻昆蟲", "animal"),
    "a kangaroo": ("一隻袋鼠", "animal"),
    "a koala": ("一隻無尾熊", "animal"),
    "an ox": ("一頭公牛", "animal"),
    "a rat": ("一隻老鼠", "animal"),
    "a spider": ("一隻蜘蛛", "animal"),
    "a turtle": ("一隻烏龜", "animal"),
    "a pet": ("一隻寵物", "animal"),
    "a cage": ("一個籠子", "animal"),
    "a ghost": ("一個鬼", "animal"),
    "a fan": ("一個歌迷", "animal"),
    "a snake": ("一條蛇", "animal"),
    "a butterfly": ("一隻蝴蝶", "animal"),
    "a mouse": ("一隻老鼠", "animal"),
    "bite a": ("咬一個", "animal"),
    "feed the": ("餵養那個", "animal"),
    "a mother bird": ("一隻鳥媽媽", "animal"),
    "in the cage": ("在籠子裡", "animal"),
    # ---- festival ----
    "a king": ("一位國王", "festival"),
    "a queen": ("一位皇后", "festival"),
    "a prince": ("一位王子", "festival"),
    "a princess": ("一位公主", "festival"),
    "a doll": ("一個洋娃娃", "festival"),
    "a candle": ("一根蠟燭", "festival"),
    "a dragon": ("一條龍", "festival"),
    "a robot": ("一個機器人", "festival"),
    "a mask": ("一個面具", "festival"),
    "a lantern": ("一個燈籠", "festival"),
    "a flute": ("一支長笛", "festival"),
    "a violin": ("一把小提琴", "festival"),
    "a guitar": ("一把吉他", "festival"),
    "a drum": ("一面鼓", "festival"),
    "a band": ("一個樂團", "festival"),
    "a comic": ("一本漫畫", "festival"),
    "a tape": ("一卷錄音帶", "festival"),
    "a video": ("一支錄影帶", "festival"),
    "a radio": ("一台收音機", "festival"),
    "a recorder": ("一台錄音機", "festival"),
    "a program": ("一個節目", "festival"),
    "a story": ("一個故事", "festival"),
    "a holiday": ("一個假日", "festival"),
    "a picnic": ("一次野餐", "festival"),
    "a festival": ("一個節慶", "festival"),
    "a present": ("一份禮物", "festival"),
    "a trick": ("一個惡作劇", "festival"),
    "christmas": ("聖誕節", "festival"),
    "halloween": ("萬聖節", "festival"),
    "easter": ("復活節", "festival"),
    "lantern festival": ("元宵節", "festival"),
    "sing a song": ("唱一首歌", "festival"),
    "dance a": ("跳一支", "festival"),
    "play the": ("演奏那個", "festival"),
    "a special": ("一個特別的", "festival"),
    "celebrate a": ("慶祝", "festival"),
    "say a wish": ("許一個願望", "festival"),
    "a barbecue": ("一場烤肉", "festival"),
    # ---- body ----
    "a neck": ("一條脖子", "body"),
    "a nose": ("一個鼻子", "body"),
    "a toe": ("一根腳趾", "body"),
    "a body": ("一個身體", "body"),
    "a finger": ("一根手指", "body"),
    "a tooth": ("一顆牙齒", "body"),
    "a nail": ("一片指甲", "body"),
    "a lip": ("一片嘴唇", "body"),
    "a heart": ("一顆心", "body"),
    "a stomach": ("一個胃", "body"),
    "a throat": ("一個喉嚨", "body"),
    "a shoulder": ("一個肩膀", "body"),
    "a mouth": ("一張嘴", "body"),
    "a headache": ("一個頭痛", "body"),
    "a fever": ("一場發燒", "body"),
    "a dentist": ("一位牙醫", "body"),
    "a nurse": ("一位護士", "body"),
    "a doctor": ("一位醫生", "body"),
    "a hospital": ("一家醫院", "body"),
    "a medicine": ("一種藥", "body"),
    "an injury": ("一處傷口", "body"),
    "a sick": ("一個生病的", "body"),
    "a weak": ("一個虛弱的", "body"),
    "a healthy": ("一個健康的", "body"),
    "a dead": ("一個死的", "body"),
    "a blind": ("一個瞎的", "body"),
    "a sore": ("一個疼痛的", "body"),
    "a sight": ("一個視力", "body"),
    "a smell": ("一種味道", "body"),
    "a smoke": ("一口菸", "body"),
    "a rest": ("一次休息", "body"),
    "brush your teeth": ("刷牙", "body"),
    "comb your hair": ("梳頭髮", "body"),
    "take a bath": ("洗澡", "body"),
    "go to bed": ("上床睡覺", "body"),
    "die": ("死", "body"),
    "die of": ("死於", "body"),
    "hurt my": ("弄傷我的", "body"),
    "feel tired": ("感到疲累", "body"),
    "feel thirsty": ("感到口渴", "body"),
    "get sick": ("生病", "body"),
    "good health": ("良好的健康", "body"),
    "do exercise": ("做運動", "body"),
    "get enough sleep": ("睡足", "body"),
    "eat healthy food": ("吃健康的食物", "body"),
    # ---- travel ----
    "a car": ("一輛車", "travel"),
    "a ship": ("一艘船", "travel"),
    "a truck": ("一輛卡車", "travel"),
    "a train": ("一列火車", "travel"),
    "a bridge": ("一座橋", "travel"),
    "a station": ("一個車站", "travel"),
    "an airport": ("一座機場", "travel"),
    "a camera": ("一台相機", "travel"),
    "a photo": ("一張照片", "travel"),
    "a map": ("一張地圖", "travel"),
    "a ticket": ("一張票", "travel"),
    "a package": ("一個包裹", "travel"),
    "a postcard": ("一張明信片", "travel"),
    "a railway": ("一條鐵路", "travel"),
    "a motorcycle": ("一台機車", "travel"),
    "a bicycle": ("一輛腳踏車", "travel"),
    "an airplane": ("一架飛機", "travel"),
    "a camp": ("一個營地", "travel"),
    "a trip": ("一趟旅行", "travel"),
    "a vacation": ("一次假期", "travel"),
    "the mrt station": ("捷運站", "travel"),
    "by ship": ("搭船", "travel"),
    "by air": ("搭飛機", "travel"),
    "arrive on time": ("準時抵達", "travel"),
    "leave early": ("提早出發", "travel"),
    "pack a": ("打包一個", "travel"),
    "sail to": ("航行到", "travel"),
    "cross the road": ("過馬路", "travel"),
    "ride a bike": ("騎腳踏車", "travel"),
    "drive a car": ("開車", "travel"),
    "stay at": ("住在", "travel"),
    "a foreign": ("一個外國的", "travel"),
    "a language": ("一種語言", "travel"),
    # ---- money ----
    "a price": ("一個價格", "money"),
    "a million": ("一百萬", "money"),
    "a hundred": ("一百", "money"),
    "a dozen": ("一打", "money"),
    "a pound": ("一磅", "money"),
    "a cent": ("一美分", "money"),
    "a piece": ("一塊", "money"),
    "a deal": ("一筆交易", "money"),
    "a wallet": ("一個錢包", "money"),
    "pay for": ("為…付錢", "money"),
    "save money": ("存錢", "money"),
    "spend money": ("花錢", "money"),
    "lend a": ("借出一個", "money"),
    "borrow a": ("借入一個", "money"),
    "a cheap": ("一個便宜的", "money"),
    "an expensive": ("一個貴的", "money"),
    "a gram": ("一公克", "money"),
    "an inch": ("一英吋", "money"),
    "a mile": ("一英哩", "money"),
    "a kilogram": ("一公斤", "money"),
    "a centimeter": ("一公分", "money"),
    "on sale": ("特價中", "money"),
    "the right size": ("剛好的尺寸", "money"),
    "a good deal": ("一筆好交易", "money"),
    # ---- work ----
    "a player": ("一位選手", "work"),
    "a worker": ("一位工作者", "work"),
    "an actor": ("一位男演員", "work"),
    "an actress": ("一位女演員", "work"),
    "a leader": ("一位領袖", "work"),
    "a reporter": ("一位記者", "work"),
    "a writer": ("一位作家", "work"),
    "an engineer": ("一位工程師", "work"),
    "a lawyer": ("一位律師", "work"),
    "a farmer": ("一位農夫", "work"),
    "a businessman": ("一位商人", "work"),
    "a secretary": ("一位秘書", "work"),
    "an officer": ("一位職員", "work"),
    "a soldier": ("一位士兵", "work"),
    "a fisherman": ("一位漁夫", "work"),
    "a meeting": ("一場會議", "work"),
    "a problem": ("一個問題", "work"),
    "a decision": ("一個決定", "work"),
    "an interview": ("一次採訪", "work"),
    "a boss": ("一位老闆", "work"),
    "a power": ("一種力量", "work"),
    "follow the rules": ("遵守規則", "work"),
    "lead a": ("帶領一個", "work"),
    "decide to": ("決定要", "work"),
    "work hard": ("努力工作", "work"),
    "work in": ("在…工作", "work"),
    # ---- nature ----
    "a park": ("一座公園", "nature"),
    "a rock": ("一塊石頭", "nature"),
    "the grass": ("草", "nature"),
    "the ground": ("地面", "nature"),
    "a lake": ("一座湖", "nature"),
    "a river": ("一條河", "nature"),
    "a plant": ("一株植物", "nature"),
    "a hill": ("一座小山", "nature"),
    "a seed": ("一顆種子", "nature"),
    "an island": ("一座島", "nature"),
    "a mountain": ("一座山", "nature"),
    "a planet": ("一顆行星", "nature"),
    "a pond": ("一個池塘", "nature"),
    "a rose": ("一朵玫瑰", "nature"),
    "a garden": ("一個花園", "nature"),
    "green": ("綠色的", "nature"),
    "grow up": ("長大", "nature"),
    "in the park": ("在公園裡", "nature"),
    "in the garden": ("在花園裡", "nature"),
    "on the hill": ("在山上", "nature"),
    "a nature": ("一種自然", "nature"),
    "the earth": ("地球", "nature"),
    # ---- sport ----
    "a race": ("一場比賽", "sport"),
    "a prize": ("一個獎項", "sport"),
    "a pin": ("一根針", "sport"),
    "a frisbee": ("一個飛盤", "sport"),
    "a badminton": ("一個羽毛球", "sport"),
    "a soccer": ("一場足球賽", "sport"),
    "a chess": ("一盤棋", "sport"),
    "a roller skate": ("一雙溜冰鞋", "sport"),
    "a dodge ball": ("一場躲避球", "sport"),
    "a seesaw": ("一座蹺蹺板", "sport"),
    "a pool": ("一座游泳池", "sport"),
    "a swing": ("一座鞦韆", "sport"),
    "go jogging": ("去慢跑", "sport"),
    "play soccer": ("踢足球", "sport"),
    "play basketball": ("打籃球", "sport"),
    "play tennis": ("打網球", "sport"),
    "play chess": ("下棋", "sport"),
    "win a": ("贏得一個", "sport"),
    "lose a": ("輸掉一個", "sport"),
    "throw a": ("丟一個", "sport"),
    "hit a": ("打中一個", "sport"),
    "hop on": ("跳上", "sport"),
    "roll a": ("滾動一個", "sport"),
    "surf": ("衝浪", "sport"),
    "do exercise": ("做運動", "sport"),
    "a sports day": ("一場運動會", "sport"),
    # ---- family ----
    "a baby": ("一個嬰兒", "family"),
    "a kid": ("一個小孩", "family"),
    "a child": ("一個孩子", "family"),
    "a brother": ("一個哥哥／弟弟", "family"),
    "a husband": ("一個丈夫", "family"),
    "a wife": ("一個妻子", "family"),
    "a neighbor": ("一位鄰居", "family"),
    "a teenager": ("一個青少年", "family"),
    "be born": ("出生", "family"),
    "raise a": ("撫養一個", "family"),
    "kiss a": ("親一個", "family"),
    "share with": ("和…分享", "family"),
    "a dear": ("一個親愛的", "family"),
    "be friendly": ("友善", "family"),
    "be married": ("結婚", "family"),
    "by myself": ("獨自", "family"),
    "do together": ("一起做", "family"),
    # ---- clothes ----
    "a cap": ("一頂鴨舌帽", "clothes"),
    "a pair": ("一雙", "clothes"),
    "a belt": ("一條皮帶", "clothes"),
    "clothes": ("衣服", "clothes"),
    "glasses": ("眼鏡", "clothes"),
    "a jacket": ("一件夾克", "clothes"),
    "a tie": ("一條領帶", "clothes"),
    "a vest": ("一件背心", "clothes"),
    "a t-shirt": ("一件T恤", "clothes"),
    "a glove": ("一隻手套", "clothes"),
    "a size": ("一個尺寸", "clothes"),
    "a skirt": ("一條裙子", "clothes"),
    "a skate": ("一雙溜冰鞋", "clothes"),
    "a tall": ("一個高的", "clothes"),
    "a short": ("一個短的", "clothes"),
    "a slim": ("一個纖細的", "clothes"),
    "the right size": ("剛好的尺寸", "clothes"),
    "wear a": ("穿著一個", "clothes"),
    "wear glasses": ("戴眼鏡", "clothes"),
    "put on": ("穿上", "clothes"),
    "school uniform": ("校服", "clothes"),
    # ---- talk ----
    "a miss": ("一位小姐", "talk"),
    "a mrs": ("一位太太", "talk"),
    "a sir": ("一位先生", "talk"),
    "a lie": ("一個謊言", "talk"),
    "a voice": ("一個聲音", "talk"),
    "a sound": ("一個聲音", "talk"),
    "never mind": ("沒關係", "talk"),
    "what do you mean": ("你的意思是什麼", "talk"),
    "what's the matter": ("發生了什麼事", "talk"),
    "i mean": ("我是說", "talk"),
    "sounds good": ("聽起來不錯", "talk"),
    "a pleasure": ("一件愉快的事", "talk"),
    "my pleasure": ("我的榮幸", "talk"),
    "a lie": ("一個謊話", "talk"),
    "tell a lie": ("說謊", "talk"),
    "tell the truth": ("說實話", "talk"),
    # ---- weather ----
    "a hot": ("一個炎熱的", "weather"),
    "a cold": ("一個寒冷的", "weather"),
    "the wind": ("風", "weather"),
    "the ice": ("冰", "weather"),
    "a rainbow": ("一道彩虹", "weather"),
    "a snowman": ("一個雪人", "weather"),
    "a typhoon": ("一個颱風", "weather"),
    "in autumn": ("在秋天", "weather"),
    "a gray": ("一個灰色的", "weather"),
    "a blue": ("一個藍色的", "weather"),
    "fall weather": ("秋天的天氣", "weather"),
})


def add_phrase(phrase, zh, sid):
    """新增一筆固定搭配。同一個片語可以掛在不同場景（例如 turn off 同時屬於
    「動作動詞」與「基礎文法」），所以值會被轉成 [(中文, 場景), ...]。"""
    entry = PHRASES.setdefault(phrase, [])
    if isinstance(entry, tuple):
        entry = [entry]
        PHRASES[phrase] = entry
    if (zh, sid) not in entry:
        entry.append((zh, sid))


# ── 第三批：補上 tools/need_phrase.txt 剩下的缺口 ──────────────────
# 純功能詞（冠詞、代名詞、be 動詞、介系詞）沒有自然的「以這個字結尾的片語」，
# 那些單元維持 3 步，這是刻意的選擇，不是漏掉。
for _ph, _zh, _sid in [
    # ---- basic：功能詞以外的搭配 ----
    ("have to", "必須", "basic"),
    ("have a", "有一個", "basic"),
    ("have fun", "玩得開心", "basic"),
    ("that is", "那就是", "basic"),
    ("this is", "這是", "basic"),
    ("that's ok", "沒關係", "basic"),
    ("are ok", "沒關係", "basic"),
    ("look yummy", "看起來很美味", "basic"),
    ("so yummy", "好美味", "basic"),
    ("very yummy", "非常美味", "basic"),
    ("turn off", "關掉", "basic"),
    ("turn on", "打開", "basic"),
    ("sit down", "坐下", "basic"),
    ("stand up", "站起來", "basic"),
    ("get up", "起床", "basic"),
    ("get out", "離開", "basic"),
    ("get in", "進入", "basic"),
    ("hold on", "等一下", "basic"),
    ("let go", "放手", "basic"),
    ("come in", "進來", "basic"),
    ("go in", "進去", "basic"),
    ("go out", "出門", "basic"),
    ("run away", "逃跑", "basic"),
    ("walk around", "到處走", "basic"),
    ("look around", "環顧四周", "basic"),
    ("stay here", "留在這裡", "basic"),
    ("do this", "做這件事", "basic"),
    ("do that", "做那件事", "basic"),
    ("does the", "做了那個", "basic"),
    ("do not have", "沒有", "basic"),
    ("do not know", "不知道", "basic"),
    ("do not like", "不喜歡", "basic"),
    ("do not want", "不想要", "basic"),
    ("do not think", "不認為", "basic"),
    ("do not care", "不在乎", "basic"),
    ("do not need", "不需要", "basic"),
    ("should do", "應該做", "basic"),
    ("should go", "應該去", "basic"),
    ("should be", "應該是", "basic"),
    ("something new", "新東西", "basic"),
    ("something important", "重要的東西", "basic"),
    ("something wrong", "不對勁的地方", "basic"),
    ("somewhere else", "別的地方", "basic"),
    ("go somewhere", "去某個地方", "basic"),
    ("nobody knows", "沒有人知道", "basic"),
    ("nobody else", "沒有別人", "basic"),
    ("nothing else", "沒有別的", "basic"),
    ("nothing to do", "無事可做", "basic"),
    ("anything else", "其他任何東西", "basic"),
    ("say anything", "說任何話", "basic"),
    ("everything ok", "一切都還好", "basic"),
    ("everything else", "其他所有東西", "basic"),
    ("is everything", "全部都", "basic"),
    ("enough money", "足夠的錢", "basic"),
    ("enough time", "足夠的時間", "basic"),
    ("good enough", "夠好了", "basic"),
    ("anyone else", "其他任何人", "basic"),
    ("would anyone", "會有人", "basic"),
    ("each one", "每一個", "basic"),
    ("each of them", "每一個", "basic"),
    ("have each", "各有一個", "basic"),
    ("even more", "更多", "basic"),
    ("even now", "即使是現在", "basic"),
    ("mean while", "同時", "basic"),
    ("what do you mean", "你的意思是什麼", "basic"),
    ("i mean", "我是說", "basic"),
    ("do you mean", "你是說", "basic"),
    ("however", "然而", "basic"),
    ("almost done", "快完成了", "basic"),
    ("already finished", "已經完成", "basic"),
    ("another one", "另一個", "basic"),
    ("another chance", "另一個機會", "basic"),
    ("because", "因為", "basic"),
    ("during the", "在…期間", "basic"),
    ("in chinese", "用中文", "basic"),
    ("speak chinese", "說中文", "basic"),
    ("either way", "無論如何", "basic"),
    ("except this", "除了這個", "basic"),
    ("except for", "除了", "basic"),
    ("less than", "少於", "basic"),
    ("more or less", "或多或少", "basic"),
    ("most important", "最重要的", "basic"),
    ("must be", "一定是", "basic"),
    ("a national", "一個國家的", "basic"),
    ("in the north", "在北部", "basic"),
    ("in the south", "在南部", "basic"),
    ("in the east", "在東部", "basic"),
    ("in the west", "在西部", "basic"),
    ("the north", "北方", "basic"),
    ("the south", "南方", "basic"),
    ("the east", "東方", "basic"),
    ("the west", "西方", "basic"),
    ("perhaps not", "也許不是", "basic"),
    ("not possible", "不可能", "basic"),
    ("a possible", "一個可能的", "basic"),
    ("on the side", "在旁邊", "basic"),
    ("a new thing", "新東西", "basic"),
    ("the same thing", "同樣的事情", "basic"),
    ("a big thing", "大事", "basic"),
    ("though", "雖然", "basic"),
    ("until now", "直到現在", "basic"),
    ("wait until", "等到", "basic"),
    ("whether or not", "無論是否", "basic"),
    ("whose bag", "誰的袋子", "basic"),
    ("without a", "沒有", "basic"),
    ("go without", "沒有也", "basic"),
    ("not yet", "還沒", "basic"),
    ("have not", "還沒有", "basic"),
    ("still here", "還在這裡", "basic"),
    ("still not", "仍然不", "basic"),
    ("a person", "一個人", "basic"),
    ("young person", "年輕人", "basic"),
    ("several people", "幾個人", "basic"),
    ("a few people", "幾個人", "basic"),
    ("own", "自己的", "basic"),
    ("on my own", "獨自", "basic"),
    ("his own", "他自己的", "basic"),
    ("a great deal", "很多", "basic"),
    ("in other words", "換句話說", "basic"),
    ("on the other hand", "另一方面", "basic"),
    ("at least", "至少", "basic"),
    ("for example", "舉例來說", "basic"),
    ("only one", "只有一個", "basic"),
    ("only a", "只有一個", "basic"),
    ("really like", "真的很喜歡", "basic"),
    ("really want", "真的很想要", "basic"),
    ("i really", "我真的很", "basic"),
    ("above", "在上面", "basic"),
    ("below", "在下面", "basic"),
    ("ahead of", "在…前面", "basic"),
    ("along with", "和…一起", "basic"),
    ("come along", "一起來", "basic"),
    ("far away", "遠遠地", "basic"),
    ("not far", "不遠", "basic"),
    ("too near", "太近", "basic"),
    ("near here", "附近", "basic"),
    ("over there", "在那裡", "basic"),
    ("over and over", "一次又一次", "basic"),
    ("up and down", "上上下下", "basic"),
    ("above all", "最重要的是", "basic"),
    ("behind you", "在你身後", "basic"),
    ("beside him", "在他旁邊", "basic"),
    ("sit beside", "坐在旁邊", "basic"),
    ("into the", "進入", "basic"),
    ("talk into", "說服", "basic"),
    ("about him", "關於他", "basic"),
    ("from above", "從上面", "basic"),
    ("once in", "每", "basic"),
    ("once again", "再一次", "basic"),
    ("ever since", "自從那時起", "basic"),
    ("have ever", "曾經", "basic"),
    ("a guy", "一個傢伙", "basic"),
    ("that guy", "那個人", "basic"),
    # ---- action ----
    ("do a", "做一個", "action"),
    ("do not", "不要", "action"),
    ("do the", "做那個", "action"),
    ("can do", "能做到", "action"),
    ("go to", "去", "action"),
    ("go out", "出門", "action"),
    ("go home", "回家", "action"),
    ("go back", "回去", "action"),
    ("go on", "繼續", "action"),
    ("go over", "過去看看", "action"),
    ("go up", "上去", "action"),
    ("go down", "下去", "action"),
    ("go away", "走開", "action"),
    ("go for a walk", "去散步", "action"),
    ("go to bed", "上床睡覺", "action"),
    ("go to school", "去上學", "action"),
    ("go to work", "去上班", "action"),
    ("nod at", "對…點頭", "action"),
    ("draw a", "畫一個", "action"),
    ("draw on", "依靠", "action"),
    ("find a", "找到一個", "action"),
    ("find out", "查明", "action"),
    ("find it", "找到它", "action"),
    ("wake the", "叫醒那個", "action"),
    ("wave to", "向…揮手", "action"),
    ("ask a", "問一個", "action"),
    ("ask for", "要求", "action"),
    ("ask about", "詢問", "action"),
    ("hang a", "掛一個", "action"),
    ("hang on to", "抓緊", "action"),
    ("join a", "加入一個", "action"),
    ("join in", "參加", "action"),
    ("keep the", "保持那個", "action"),
    ("keep a", "保持一個", "action"),
    ("touch the", "觸碰那個", "action"),
    ("touch on", "略述", "action"),
    ("take action", "採取行動", "action"),
    ("break a", "打破一個", "action"),
    ("take a break", "休息一下", "action"),
    ("carry a", "提著一個", "action"),
    ("carry on", "繼續", "action"),
    ("dig a", "挖一個", "action"),
    ("go hunting", "去打獵", "action"),
    ("kill a", "殺死一個", "action"),
    ("become a", "成為一個", "action"),
    ("begin with", "以…開始", "action"),
    ("build a", "建造一個", "action"),
    ("burn a", "燒掉一個", "action"),
    ("check on", "查看", "action"),
    ("choose a", "選擇一個", "action"),
    ("choose to", "選擇要", "action"),
    ("collect a", "收集一個", "action"),
    ("collect stamps", "收集郵票", "action"),
    ("cover a", "蓋住一個", "action"),
    ("cover up", "遮蓋", "action"),
    ("drop a", "掉落一個", "action"),
    ("drop by", "順路拜訪", "action"),
    ("forget to", "忘了要", "action"),
    ("guess a", "猜一個", "action"),
    ("guess what", "猜猜看", "action"),
    ("knock on", "敲打", "action"),
    ("knock down", "敲倒", "action"),
    ("pick up", "撿起", "action"),
    ("pick a", "挑選一個", "action"),
    ("pull a", "拉一個", "action"),
    ("pull over", "靠邊停", "action"),
    ("remember to", "記得要", "action"),
    ("remember me", "記得我", "action"),
    ("repeat after", "在…之後重複", "action"),
    ("shout at", "對…吼叫", "action"),
    ("shout for", "大喊要", "action"),
    ("understand a", "理解一個", "action"),
    ("do not understand", "不懂", "action"),
    ("watch a", "看一個", "action"),
    ("watch tv", "看電視", "action"),
    ("appear in", "出現在", "action"),
    ("appear to", "看起來", "action"),
    ("attack a", "攻擊一個", "action"),
    ("belong to", "屬於", "action"),
    ("belong here", "屬於這裡", "action"),
    ("blow a", "吹一個", "action"),
    ("blow out", "吹熄", "action"),
    ("the wind blows", "風吹著", "action"),
    ("clap a", "拍一個", "action"),
    ("clap for", "為…鼓掌", "action"),
    ("count on", "依靠", "action"),
    ("count from", "從…開始數", "action"),
    ("enter a", "進入一個", "action"),
    ("enter the", "進入那個", "action"),
    ("fight with", "和…打架", "action"),
    ("fight for", "為了…而戰鬥", "action"),
    ("fill a", "裝滿一個", "action"),
    ("fill with", "裝滿", "action"),
    ("finish a", "完成一個", "action"),
    ("finish the", "完成那個", "action"),
    ("fix a", "修理一個", "action"),
    ("fix the", "修理那個", "action"),
    ("what happened", "發生了什麼事", "action"),
    ("hide a", "藏起一個", "action"),
    ("hide behind", "藏在後面", "action"),
    ("notice a", "注意到一個", "action"),
    ("notice that", "注意到", "action"),
    ("shake a", "搖晃一個", "action"),
    ("shake hands", "握手", "action"),
    # ---- food ----
    ("an apple", "一個蘋果", "food"),
    ("apple pie", "蘋果派", "food"),
    ("eat a", "吃一個", "food"),
    ("eat well", "吃得好", "food"),
    ("fry an", "煎一個", "food"),
    ("fry eggs", "煎蛋", "food"),
    ("a ham", "一片火腿", "food"),
    ("ham and", "火腿和", "food"),
    ("bake a", "烤一個", "food"),
    ("bake cookies", "烤餅乾", "food"),
    ("very delicious", "非常美味", "food"),
    ("so delicious", "真好吃", "food"),
    ("a fork", "一把叉子", "food"),
    ("with a fork", "用叉子", "food"),
    ("an orange", "一顆柳橙", "food"),
    ("orange juice", "柳橙汁", "food"),
    ("order a", "點一份", "food"),
    ("order food", "點餐", "food"),
    ("a spoon", "一支湯匙", "food"),
    ("with a spoon", "用湯匙", "food"),
    ("the water boils", "水滾了", "food"),
    ("boil an", "煮沸一個", "food"),
    ("a bun", "一個小麵包", "food"),
    ("eat with", "用…吃", "food"),
    ("chopsticks", "筷子", "food"),
    ("a clerk", "一位店員", "food"),
    ("a shopkeeper", "一位店長", "food"),
    ("a salesman", "一位銷售員", "food"),
    ("the cost", "花費", "food"),
    ("cost a", "花費", "food"),
    ("a guava", "一顆芭樂", "food"),
    ("too much oil", "太多油", "food"),
    ("a papaya", "一顆木瓜", "food"),
    ("a plate", "一個盤子", "food"),
    ("on the plate", "在盤子上", "food"),
    ("a pumpkin", "一個南瓜", "food"),
    ("pumpkin pie", "南瓜派", "food"),
    ("a strawberry", "一顆草莓", "food"),
    ("taste good", "嘗起來很好", "food"),
    ("taste like", "嘗起來像", "food"),
    # ---- school ----
    ("read a", "讀一個", "school"),
    ("read to", "讀給…聽", "school"),
    ("be proud", "感到驕傲", "school"),
    ("spell a", "拼出", "school"),
    ("spell the", "拼出那個", "school"),
    ("copy a", "抄一個", "school"),
    ("copy and paste", "複製貼上", "school"),
    ("a correct", "一個正確的", "school"),
    ("correct answer", "正確答案", "school"),
    ("mark the", "標記那個", "school"),
    ("a piece of paper", "一張紙", "school"),
    ("on the paper", "在紙上", "school"),
    ("a type", "一種類型", "school"),
    ("this type", "這種", "school"),
    ("music class", "音樂課", "school"),
    ("pass the", "通過那個", "school"),
    ("make a plan", "訂計畫", "school"),
    ("a plan", "一個計畫", "school"),
    ("front row", "前排", "school"),
    ("a club", "一個社團", "school"),
    ("join a club", "加入社團", "school"),
    ("a dictionary", "一本字典", "school"),
    ("look up", "查閱", "school"),
    ("an example", "一個例子", "school"),
    ("for example", "舉例來說", "school"),
    ("a hard-working", "一個勤勞的", "school"),
    ("hard-working person", "勤勞的人", "school"),
    ("our history", "我們的歷史", "school"),
    ("the history of", "…的歷史", "school"),
    ("math class", "數學課", "school"),
    ("good at math", "擅長數學", "school"),
    ("copy and", "複製並", "school"),
    ("science class", "科學課", "school"),
    ("knowledge", "知識", "school"),
    ("learn knowledge", "學知識", "school"),
    ("paste", "黏貼", "school"),
    ("copy and paste", "複製並貼上", "school"),
    # ---- time ----
    ("see you later", "待會見", "time"),
    ("much later", "晚很多", "time"),
    ("very soon", "很快", "time"),
    ("soon", "很快", "time"),
    ("always", "總是", "time"),
    ("not always", "並非總是", "time"),
    ("often", "時常", "time"),
    ("how often", "多常", "time"),
    ("once more", "再一次", "time"),
    ("seldom", "很少", "time"),
    ("since then", "從那時起", "time"),
    ("ever since", "自從那時起", "time"),
    ("on sunday", "在星期日", "time"),
    ("on thursday", "在星期四", "time"),
    ("on tuesday", "在星期二", "time"),
    ("on wednesday", "在星期三", "time"),
    ("tonight", "今晚", "time"),
    ("twice", "兩次", "time"),
    ("twice a week", "一週兩次", "time"),
    ("a century", "一個世紀", "time"),
    ("century", "世紀", "time"),
    ("the end", "結束", "time"),
    ("come to an end", "來到終點", "time"),
    ("new year's eve", "除夕夜", "time"),
    ("at the moment", "目前", "time"),
    ("this moment", "這一刻", "time"),
    # ---- feeling ----
    ("so mad", "非常生氣", "feeling"),
    ("get mad", "生氣", "feeling"),
    ("cry a", "哭出", "feeling"),
    ("cry for", "為…哭泣", "feeling"),
    ("hope for", "希望", "feeling"),
    ("i hope", "我希望", "feeling"),
    ("worry about", "擔心", "feeling"),
    ("a smile", "一個微笑", "feeling"),
    ("smile at", "對…微笑", "feeling"),
    ("be unhappy", "不快樂", "feeling"),
    ("get angry", "生氣", "feeling"),
    ("be angry at", "對…生氣", "feeling"),
    ("believe that", "相信", "feeling"),
    ("i believe", "我相信", "feeling"),
    ("take care", "保重", "feeling"),
    ("a chance", "一個機會", "feeling"),
    ("have a chance", "有機會", "feeling"),
    ("very exciting", "非常令人興奮", "feeling"),
    ("be helpful", "有幫助的", "feeling"),
    ("a helpful", "一個有幫助的", "feeling"),
    ("show interest", "表現出興趣", "feeling"),
    ("have no interest", "沒有興趣", "feeling"),
    ("feel lonely", "感到寂寞", "feeling"),
    ("too loud", "太大聲", "feeling"),
    ("loud noise", "很大的噪音", "feeling"),
    ("a lovely", "一個可愛的", "feeling"),
    ("be quiet", "保持安靜", "feeling"),
    ("stay quiet", "保持安靜", "feeling"),
    # ---- home ----
    ("draw a line", "劃一條線", "home"),
    ("a long line", "一條長長的隊伍", "home"),
    ("on the top", "在最上面", "home"),
    ("the top", "頂部", "home"),
    ("fresh air", "新鮮空氣", "home"),
    ("mop the", "拖那個", "home"),
    ("mop the floor", "拖地板", "home"),
    ("mud on", "泥巴在", "home"),
    ("clean the mud", "清掉泥巴", "home"),
    ("make a noise", "製造噪音", "home"),
    ("a noise", "一聲噪音", "home"),
    ("the stairs", "樓梯", "home"),
    ("on the stairs", "在樓梯上", "home"),
    ("a big base", "一個大底座", "home"),
    ("an apartment", "一間公寓", "home"),
    ("at the bottom", "在底部", "home"),
    ("the bottom", "底部", "home"),
    ("in the refrigerator", "在冰箱裡", "home"),
    ("use the restroom", "使用廁所", "home"),
    ("take out the trash", "倒垃圾", "home"),
    ("a lot of space", "很多空間", "home"),
    ("make space", "騰出空間", "home"),
    ("take up space", "佔空間", "home"),
    # ---- describe ----
    ("get fat", "變胖", "describe"),
    ("too fat", "太胖", "describe"),
    ("a fat", "一個胖的", "describe"),
    ("six feet", "六呎", "describe"),
    ("medium size", "中號", "describe"),
    ("quite a", "相當一個", "describe"),
    ("quite good", "相當不錯", "describe"),
    ("shine", "閃耀", "describe"),
    ("the sun shines", "太陽閃耀", "describe"),
    ("become famous", "變得有名", "describe"),
    ("a famous", "一個有名的", "describe"),
    ("so important", "非常重要", "describe"),
    ("very important", "非常重要", "describe"),
    ("low voice", "低低的聲音", "describe"),
    ("modern times", "現代", "describe"),
    ("in modern", "在現代", "describe"),
    ("round table", "圓桌", "describe"),
    ("a round", "一個圓的", "describe"),
    ("a shape", "一種形狀", "describe"),
    ("different shapes", "不同的形狀", "describe"),
    ("be successful", "成功", "describe"),
    ("a successful", "一個成功的", "describe"),
    ("very thick", "非常厚", "describe"),
    ("thick and", "厚而且", "describe"),
    ("really useful", "真的很有用", "describe"),
    ("useful books", "有用的書", "describe"),
    # ---- sport ----
    ("go jogging", "去慢跑", "sport"),
    ("play a", "玩一個", "sport"),
    ("play with", "和…玩", "sport"),
    ("play basketball", "打籃球", "sport"),
    ("play ping-pong", "打桌球", "sport"),
    ("throw a", "丟一個", "sport"),
    ("throw the", "丟那個", "sport"),
    ("hop on", "跳上", "sport"),
    ("see a", "看到一個", "sport"),
    ("see the", "看到那個", "sport"),
    ("a slide", "一座滑梯", "sport"),
    ("hit a", "打中一個", "sport"),
    ("hit the", "打到那個", "sport"),
    ("kick a", "踢一個", "sport"),
    ("kick the", "踢那個", "sport"),
    ("lose a", "輸掉一個", "sport"),
    ("lose the", "輸掉那個", "sport"),
    ("roll a", "滾動一個", "sport"),
    ("roll over", "翻滾", "sport"),
    ("win a", "贏得一個", "sport"),
    ("win the", "贏得那個", "sport"),
    ("play dodge ball", "打躲避球", "sport"),
    ("roller-skate", "溜四輪溜冰", "sport"),
    # ---- city ----
    ("live in", "住在", "city"),
    ("a market", "一個市場", "city"),
    ("at the market", "在市場裡", "city"),
    ("go to the market", "去市場", "city"),
    ("a museum", "一座博物館", "city"),
    ("go to the museum", "去博物館", "city"),
    ("inside", "在裡面", "city"),
    ("outside", "在外面", "city"),
    ("mail", "郵件", "city"),
    ("send an e-mail", "寄一封電子郵件", "city"),
    ("the usa", "美國", "city"),
    ("in america", "在美國", "city"),
    ("an american", "一個美國人", "city"),
    ("a chinese", "一個中國人", "city"),
    ("the department store", "百貨公司", "city"),
    ("at the department store", "在百貨公司", "city"),
    # ---- travel ----
    ("the way", "方法", "travel"),
    ("a way", "一種方式", "travel"),
    ("fly a", "放飛一個", "travel"),
    ("fly to", "飛往", "travel"),
    ("out of gas", "沒油了", "travel"),
    ("leave for", "出發前往", "travel"),
    ("leave early", "提早離開", "travel"),
    ("stay at", "住在", "travel"),
    ("a foreigner", "一個外國人", "travel"),
    ("pack a", "打包一個", "travel"),
    ("pack for", "為…打包", "travel"),
    ("arrive at", "抵達", "travel"),
    ("arrive home", "到家", "travel"),
    ("heavy traffic", "交通壅塞", "travel"),
    ("the traffic", "交通", "travel"),
    # ---- money ----
    ("save up", "儲蓄", "money"),
    ("save money", "存錢", "money"),
    ("lend a", "借出一個", "money"),
    ("lend me", "借我", "money"),
    ("change the", "改變那個", "money"),
    ("borrow from", "向…借", "money"),
    ("borrow a", "借入一個", "money"),
    ("do business", "做生意", "money"),
    ("a businessman", "一位商人", "money"),
    ("spend a", "花費一個", "money"),
    ("spend the", "花費那個", "money"),
    # ---- work ----
    ("lead a", "帶領一個", "work"),
    ("lead the", "帶領那個", "work"),
    ("a fire", "一場火", "work"),
    ("decide to", "決定要", "work"),
    ("decide on", "決定好", "work"),
    ("follow a", "遵守一個", "work"),
    ("follow me", "跟我走", "work"),
    ("be lazy", "懶惰", "work"),
    ("a lazy", "一個懶惰的", "work"),
    ("fishermen", "漁夫們", "work"),
    # ---- animal ----
    ("a swing", "一座鞦韆", "animal"),
    ("play on the swing", "玩鞦韆", "animal"),
    ("a bat", "一隻蝙蝠", "animal"),
    ("bite a", "咬一個", "animal"),
    ("bite people", "咬人", "animal"),
    ("a tail", "一條尾巴", "animal"),
    ("a goose", "一隻鵝", "animal"),
    # ---- festival ----
    ("dance a", "跳一支", "festival"),
    ("dance with", "和…跳舞", "festival"),
    ("magic power", "魔力", "festival"),
    ("act in", "演出於", "festival"),
    ("act a", "演出", "festival"),
    ("celebrate a", "慶祝", "festival"),
    ("celebrate with", "和…一起慶祝", "festival"),
    ("pray for", "為…祈禱", "festival"),
    # ---- family ----
    ("kiss a", "親一個", "festival"),
    ("raise a", "撫養一個", "family"),
    ("raise up", "撫養長大", "family"),
    ("by himself", "他自己", "family"),
    ("help himself", "幫他自己", "family"),
    ("share a", "分享一個", "family"),
    ("share with", "和…分享", "family"),
    # ---- nature ----
    ("a lot of land", "很多土地", "nature"),
    ("grow up", "長大", "nature"),
    ("grow fast", "長得很快", "nature"),
    ("fly a kite", "放風箏", "nature"),
    ("the sun rises", "太陽升起", "nature"),
    ("rise up", "升起", "nature"),
    # ---- body / talk / weather / clothes ----
    ("a sore throat", "喉嚨痛", "body"),
    ("hurt a", "弄傷一個", "body"),
    ("smoke a", "抽一口", "body"),
    ("take medicine", "吃藥", "body"),
    ("see a doctor", "看醫生", "body"),
    ("see the doctor", "看醫生", "body"),
    ("what's wrong", "哪裡不對", "body"),
    ("dear sir", "親愛的先生", "talk"),
    ("yes sir", "是的先生", "talk"),
    ("no problem", "沒問題", "talk"),
    ("who's that", "那是誰", "talk"),
    ("a cold day", "一個冷天", "weather"),
    ("the cold", "寒冷", "weather"),
    ("a warm day", "一個溫暖的日子", "weather"),
    ("a hot day", "一個炎熱的日子", "weather"),
    ("a coat", "一件外套", "clothes"),
    ("wear a hat", "戴一頂帽子", "clothes"),
    ("in the cold", "在寒冷中", "weather"),
    # ---- 針對例句很短、只能做出 2 步的單元，盡量再補一個真實搭配 ----
    ("i can", "我可以", "basic"),
    ("she can", "她可以", "basic"),
    ("be able", "能夠", "basic"),
    ("i agree", "我同意", "basic"),
    ("you must", "你必須", "basic"),
    ("still here", "還在這裡", "basic"),
    ("behind her", "在她後面", "basic"),
    ("behind him", "在他後面", "basic"),
    ("work experience", "工作經驗", "basic"),
    ("no experience", "沒有經驗", "basic"),
    ("already done", "已經完成", "basic"),
    ("bad dreams", "惡夢", "basic"),
    ("kiss mom", "親媽媽", "family"),
    ("her mom", "她的媽媽", "family"),
    ("raised her", "撫養她", "family"),
    ("copy her", "抄她的", "school"),
    ("homework", "家庭作業", "school"),
    ("fry eggs", "煎蛋", "food"),
    ("tastes good", "嘗起來很好", "food"),
    ("grow fast", "長得很快", "nature"),
    ("plants grow", "植物生長", "nature"),
    ("comb hair", "梳頭髮", "body"),
    ("where do you", "你在哪裡", "city"),
    ("birds can", "鳥兒可以", "travel"),
    ("can fly", "會飛", "travel"),
    ("the train", "這列火車", "travel"),
    ("stay here", "留在這裡", "travel"),
    ("packing for", "為…打包", "travel"),
    ("spend too much", "花費太多", "money"),
    ("did you", "你有沒有", "sport"),
    ("dances well", "舞跳得很好", "festival"),
    ("will be", "將會是", "feeling"),
    ("don’t worry", "別擔心", "feeling"),
    ("don’t be", "不要", "feeling"),
    ("do not touch", "不要碰", "action"),
    ("can not", "不能", "action"),
    # 原本這裡有 ("can’t", "不能", "action")：它是單一個縮寫、查不到音標，
    # 卻會在 in_sent 分支搶先命中（例如 "I can't find him."），害那幾個單元
    # 拿到一個沒有音標、也沒東西可學的「詞組」。已移除，改用真正可學的語塊。
    ("did not", "沒有", "action"),
    ("does not", "不", "action"),
    ("do not come", "不要來", "action"),
    ("do not say", "不要說", "action"),
]:
    add_phrase(_ph, _zh, _sid)

# ── 第四批：讓每個單元都一定有「詞組」那一關 ──────────────────────
# 挑法：一律取自該單元自己的例句（in_sent 一定配得到），所以學的是
# 自己正在讀、正在打的那一句裡真正會出現的語塊，不是憑空生出來的搭配。
for _ph, _zh, _sid in [
    # ---- basic ----
    ("studies very hard", "非常用功唸書", "basic"),
    ("under the trees", "在樹子底下", "basic"),
    ("doesn't know", "不知道", "basic"),
    ("even a five-year-old kid", "就連五歲的小孩", "basic"),
    ("nobody's home", "沒有人在家", "basic"),
    ("got nothing", "什麼都沒得到", "basic"),
    ("something to drink", "喝的東西", "basic"),
    ("still works here", "仍在這裡工作", "basic"),
    ("take off their shoes", "把鞋子脫掉", "basic"),
    ("knows the answer", "知道答案", "basic"),
    ("other people", "其他人", "basic"),
    ("shall we leave", "我們可以走了嗎", "basic"),
    ("almost ten o'clock", "快要十點", "basic"),
    ("years old", "歲", "basic"),
    ("another way", "另一個方法", "basic"),
    ("don't want to go", "不想去", "basic"),
    ("all my classmates", "我所有的同學", "basic"),
    ("finally got the answer", "終於得到了答案", "basic"),
    ("the most difficult", "最難的", "basic"),
    ("will say yes", "會答應", "basic"),
    ("don't know whether", "不知道是否", "basic"),
    ("whose notebook", "誰的筆記本", "basic"),
    # ---- family ----
    ("kissed mom", "親了媽媽", "family"),
    ("share things", "分享東西", "family"),
    # ---- home ----
    ("mops the floor", "拖地板", "home"),
    # ---- school ----
    ("read these three pages", "讀這三頁", "school"),
    ("spell this word", "拼這個字", "school"),
    ("mark this part", "標記這個部分", "school"),
    ("listened to music", "聽音樂", "school"),
    ("passed the test", "通過考試", "school"),
    ("is interesting", "很有趣", "school"),
    # ---- food ----
    ("like to eat", "喜歡吃", "food"),
    ("fries eggs", "炒蛋", "food"),
    ("bakes a cake", "烤一個蛋糕", "food"),
    ("ready to order", "準備好要點餐", "food"),
    ("is boiling", "正在沸騰", "food"),
    # ---- animal ----
    ("bites people", "咬人", "animal"),
    # ---- weather ----
    ("seldom snows", "很少下雪", "weather"),
    # ---- time ----
    ("once a month", "每個月一次", "time"),
    # ---- body ----
    ("brush my teeth", "刷牙", "body"),
    ("cut my finger", "割到手指", "body"),
    ("good for your health", "對你的健康有益", "body"),
    ("combs my hair", "梳頭髮", "body"),
    # ---- clothes ----
    ("wear gloves", "戴手套", "clothes"),
    # ---- city ----
    ("in taiwan", "在台灣", "city"),
    ("a big country", "一個很大的國家", "city"),
    # ---- travel ----
    ("back home", "回到家", "travel"),
    # ---- money ----
    ("saved the princess", "救出了公主", "money"),
    ("lend my car", "把我的車借出去", "money"),
    ("change your mind", "改變心意", "money"),
    ("borrow your dictionary", "借你的字典", "money"),
    # ---- work ----
    ("decided to go", "決定要去", "work"),
    ("follow these rules", "遵守這些規定", "work"),
    # ---- sport ----
    ("goes jogging", "去慢跑", "sport"),
    ("play table tennis", "打桌球", "sport"),
    ("throw it away", "把它丟掉", "sport"),
    ("is hopping", "正在跳", "sport"),
    ("don't hit", "不要打", "sport"),
    ("are kicking the soccer", "正在踢足球", "sport"),
    ("under the blanket", "在毯子下面", "sport"),
    ("win this game", "贏得這場比賽", "sport"),
    # ---- festival ----
    ("dances very well", "舞跳得很好", "festival"),
    ("acts snow white", "扮演白雪公主", "festival"),
    ("will celebrate", "會慶祝", "festival"),
    # ---- feeling ----
    ("is crying", "正在哭", "feeling"),
    # ---- action ----
    ("go with you", "和你一起去", "action"),
    ("nodded to me", "對我點頭", "action"),
    ("draw an elephant", "畫一隻大象", "action"),
    ("can't find him", "找不到他", "action"),
    ("wake you up", "叫醒你", "action"),
    ("waving at me", "對我揮手", "action"),
    ("ask questions", "問問題", "action"),
    ("hang the picture", "掛那幅畫", "action"),
    ("join us", "加入我們", "action"),
    ("keep these books", "保留這些書", "action"),
    ("carry too much money", "帶太多錢在身上", "action"),
    ("digging on the ground", "在地上挖土", "action"),
    ("goes hunting", "去打獵", "action"),
    ("killed the man", "殺了那個男人", "action"),
    ("became very quiet", "變得非常安靜", "action"),
    ("when will the show begin", "表演什麼時候開始", "action"),
    ("ten years ago", "十年前", "action"),
    ("burning in the kitchen", "在廚房裡燒起來了", "action"),
    ("check your answers", "檢查你的答案", "action"),
    ("choose the red one", "選紅色的那個", "action"),
    ("a lot of stamps", "很多郵票", "action"),
    ("covers his bed", "蓋住他的床", "action"),
    ("don't drop the juice", "不要把果汁滴落", "action"),
    ("don't forget your bag", "別忘了你的包包", "action"),
    ("let me guess", "讓我猜猜看", "action"),
    ("knocking on the door", "敲門", "action"),
    ("pulled his sister down", "把妹妹拉坐下來", "action"),
    ("remember his name", "記得他的名字", "action"),
    ("watch ball games", "看球賽", "action"),
    ("behind the trees", "在樹子後面", "action"),
    ("attacked the old lady", "攻擊那位老太太", "action"),
    ("belongs to", "屬於", "action"),
    ("is blowing hard", "颳得很大", "action"),
    ("enter this room", "進入這個房間", "action"),
    ("fill the bottle with water", "把瓶子裝滿水", "action"),
    ("have to finish it", "必須把它完成", "action"),
    ("under the bed", "在床下", "action"),
    ("shake your body", "搖動身體", "action"),
    # ---- describe ----
    ("six candles", "六根蠟燭", "describe"),
    ("small or medium", "小的或中型的", "describe"),
    ("quite short", "相當短", "describe"),
    ("keep your voice low", "把音量放低", "describe"),
    # ---- talk ----
    ("i agree with you", "我同意你", "talk"),
    ("what's up", "最近怎麼樣", "talk"),
    ("have any ideas", "有什麼點子嗎", "talk"),
]:
    add_phrase(_ph, _zh, _sid)

# 統一格式：把前兩批的 (中文, 場景) 也轉成 [(中文, 場景), ...]，
# 這樣同一個片語才能同時掛在多個場景底下（例如 turn off 既是動作也是基礎文法）。
for _k, _v in list(PHRASES.items()):
    if isinstance(_v, tuple):
        PHRASES[_k] = [_v]

TOKEN_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9'’\-]*")


def flat(s):
    """把句子與片語壓成同一種「只有小寫字母、數字與空白」的形式再比對。

    片語裡的 don't / what's / five-year-old 帶撇號與連字號，
    句子上那邊會被 [^a-z0-9 ] 換成空白（doesn t / what s / five year old）。
    片語這邊不做同樣的處理就永遠配不上，所以兩邊都走 flat()。
    """
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9 ]+", " ", s.lower())).strip()

# 英文裡「排版好看但鍵盤打不出來」的字元 → 半形對應字元
PUNCT_TYPABLE = {
    "‘": "'", "’": "'", "‚": "'",
    "“": '"', "”": '"', "„": '"',
    "–": "-", "—": "-", "−": "-",
    "…": "...",
}
TYPEABLE_COUNT = {"n": 0}     # 換掉幾個字，寫進 build 報告


def typeable(s):
    """把英文換成鍵盤打得到的半形字元。只用在英文欄位。"""
    for a, b in PUNCT_TYPABLE.items():
        if a in s:
            TYPEABLE_COUNT["n"] += s.count(a)
            s = s.replace(a, b)
    return s


def to_typeable(banks):
    """走訪所有單元，把 target 與每一步的 en 都換成半形。

    ipa 與 zh 一律不動——IPA 裡的 ˈ ː ɡ ʌ ɹ ʃ 等本來就是非 ASCII，
    而且顯示音標時應該維持原樣。
    """
    for b in banks:
        for u in b["units"]:
            u["target"] = typeable(u["target"])
            for st in u["steps"]:
                st["en"] = typeable(st["en"])


# ---- 音標（tools/ipa.json，由 tools/fetch_ipa.py 從 CMUdict 產生）----
IPA_FILE = ROOT / "tools" / "ipa.json"
IPA = json.loads(IPA_FILE.read_text(encoding="utf-8")) if IPA_FILE.exists() else {}


def ipa_of(word):
    """查一個字的音標；查不到就逐字拆開再拼（處理 "French fries"、"T-shirt"）。"""
    if not IPA:
        return ""
    # PDF 的例句用 U+2019（can’t），CMUdict 的 key 用 U+0027（can't）。
    # 不先轉換的話，例句裡所有帶撇號的字都查不到，會被整個從音標裡漏掉，
    # 變成 "I can't find him." → /ˈaɪ ˈfaɪnd ˈhɪm/。
    word = word.translate(IPA_APOS)
    key = norm(word)
    if key in IPA:
        return IPA[key]
    parts = [norm(p) for p in re.split(r"[^A-Za-z'’]+", word) if norm(p)]
    got = [IPA[p] for p in parts if p in IPA]
    return " ".join(got)


def ipa_of_sentence(sent):
    """整句音標：逐詞查得到就拼起來，查不到的（多為人名）略過。"""
    out = []
    for tok in sent.split():
        core = re.match(r"^[A-Za-z'’\-]+", tok)
        if not core:
            continue
        got = ipa_of(core.group(0))
        if got:
            out.append(got)
    return " ".join(out)


# 查 CMUdict 之前先把排版撇號換成 ASCII 撇號
IPA_APOS = str.maketrans({"’": "'", "‘": "'", "ʼ": "'"})


def main():
    entries = json.loads(LEX.read_text(encoding="utf-8"))["entries"]
    by_id = {e["id"]: e for e in entries}

    # ---- 場景指派 ----
    from scenarios import lookup
    scen_of = lookup()
    # 指定少數同形異義的條目（do 做 / do 助動詞、miss 小姐 / miss 想念）
    id_override = {"1-014": "action", "4-029": "basic", "1-042": "talk", "2-047": "feeling"}

    assigned, unmapped = {}, []
    for e in entries:
        sid = id_override.get(e["id"])
        if not sid:
            k = norm(e["word"])
            # 多字單字先試整串，再試第一個字
            sid = scen_of.get(k) or scen_of.get(k.split(" ")[0])
        if not sid:
            unmapped.append(e["id"])
            sid = "describe"
        assigned[e["id"]] = sid

    # ---- 建立單字索引（用來從例句中撈其他字，附上真實中文釋義）----
    gloss = {}
    for e in entries:
        k = norm(e["word"])
        if k and k not in gloss:
            gloss[k] = (e["word"], e["zh"], e["id"])

    # ---- 組單元 ----
    STOP = set("""a an the is am are was were be been being do does did
        have has had i he she it we they you my your his her its our their this
        that these those there here not no and or but if so very too also just
        to of in on at for with from by up down out into over under about as
        it its he she they we""".split())

    banks, phrases_used = [], set()
    for sid, title, icon, desc in SCENARIOS:
        items = [e for e in entries if assigned[e["id"]] == sid]
        items.sort(key=lambda e: (e["level"], e["seq"]))
        units = []
        for e in items:
            toks = [t for t in TOKEN_RE.findall(e["ex_en"]) if t.lower() not in STOP]

            # 候選的「單字步驟」：同一句例句裡出現、而且字庫中有釋義的其他字
            seen = {norm(e["word"])}
            extra_words = []
            for t in toks:
                k = norm(t)
                if k in gloss and k not in seen and gloss[k][1]:
                    seen.add(k)
                    extra_words.append({"kind": "word", "en": gloss[k][0],
                                        "zh": gloss[k][1], "src": gloss[k][2]})

            # 詞組步驟：只能用「人工對照表」裡的固定搭配。
            # 不用「把兩個字的釋義直接串起來」——那會產生「書厚的」「應該答案」
            # 這種讀不通的中文，對學習者是負面效果。
            low = " " + flat(e["ex_en"]) + " "
            # 目標字可能本身是多字（"everyone everybody"、"goose / geese"），
            # 比對時取第一個字當代表，避免這類條目永遠配不到片語。
            tgt = norm(e["word"])
            tgt_key = tgt.split(" ")[0] if tgt else ""
            in_sent, by_target = None, None
            # 注意：迴圈變數不要叫 entries，會蓋掉外層的字庫清單
            for ph, ph_entries in PHRASES.items():
                for zh, ph_sid in ph_entries:
                    if ph_sid != sid:
                        continue
                    # 詞組步驟在畫面上要顯示音標，查不到音標的片語一律不採用，
                    # 否則會出現「整格空白、只有一條底線」的情況。
                    if not ipa_of_sentence(ph):
                        continue
                    if in_sent is None and " " + flat(ph) + " " in low:
                        in_sent = (ph, zh)
                    if by_target is None and norm(ph.split()[-1]) in (tgt, tgt_key):
                        by_target = (ph, zh)
            found = in_sent or by_target

            # 固定成「3 個內容步驟 + 整句」＝最多 4 步，長度一致比較好規律。
            # 詞組優先放在單字之後；不夠的話就用同一句裡的其他單字補位。
            steps = [{"kind": "word", "en": e["word"], "zh": e["zh"], "src": e["id"]}]
            if found:
                steps.append({"kind": "phrase", "en": found[0], "zh": found[1], "src": "table"})
                phrases_used.add(found[0])
            while extra_words and len(steps) < 3:
                steps.append(extra_words.pop(0))

            # step 最後：整句
            steps.append({"kind": "sentence", "en": e["ex_en"], "zh": e["ex_zh"],
                          "src": e["id"]})

            # 每一步都補上音標（查不到的詞會被略過，例如人名）
            for st in steps:
                st["ipa"] = ipa_of_sentence(st["en"]) if IPA else ""

            units.append({
                "id": e["id"],
                "level": e["level"],
                "target": e["word"],
                "gloss": e["zh"],
                "ipa": ipa_of(e["word"]),
                "steps": steps,
            })
        if units:
            banks.append({"id": sid, "title": title, "icon": icon, "desc": desc,
                          "units": units})

    # ---- 打字機化：把英文裡打不出來的排版字元換成半形 ----
    # PDF 用的是 U+2019（’），但一般鍵盤按 Shift+2 得到的是 "，
    # 學生永遠打不出來，會被 App 判成錯字。改成 U+0027（'），
    # 讓「顯示出來的」就是「打得出來的」。
    # 注意：只套用在英文欄位，絕不能碰 IPA（裡面有 ˈ ː ɡ ʌ 等）與中文。
    to_typeable(banks)

    total_steps = sum(len(u["steps"]) for b in banks for u in b["units"])
    OUT.parent.mkdir(exist_ok=True)
    payload = {"scenarios": banks, "totalEntries": len(entries)}
    OUT.write_text(
        "/* 由 tools/build_bank.py 自動產生，請勿手改。\n"
        "   來源：英語單字口袋書（1-6級）.pdf（889 條，已校對） */\n"
        "window.BANKS = " + json.dumps(payload, ensure_ascii=False, indent=1) + ";\n",
        encoding="utf-8")

    lines = [f"entries={len(entries)}  scenarios={len(banks)}  "
             f"units={sum(len(b['units']) for b in banks)}  steps={total_steps}",
             f"unmapped={len(unmapped)}",
             f"ipa_table={len(IPA)}  units_with_ipa="
             f"{sum(1 for b in banks for u in b['units'] if u['ipa'])}  "
             f"steps_with_ipa="
             f"{sum(1 for b in banks for u in b['units'] for s in u['steps'] if s['ipa'])}",
             f"typography_fixed={TYPEABLE_COUNT['n']}  "
             f"(英文裡 U+2019 等排版字元已換成鍵盤打得到的半形)"]
    lines += ["  UNMAPPED " + u for u in unmapped]
    lines.append("")
    for b in banks:
        lv = {}
        for u in b["units"]:
            lv[u["level"]] = lv.get(u["level"], 0) + 1
        lines.append(f"{b['id']:9s} {b['icon']} {b['title']:6s} units={len(b['units']):3d} "
                     f"levels={dict(sorted(lv.items()))}")
    lines.append("")
    lines.append(f"phrases used={len(phrases_used)} / {len(PHRASES)}")
    unused = [p for p in PHRASES if p not in phrases_used]
    lines.append("unused phrases: " + ", ".join(unused))

    # 還缺詞組步驟的單元：寫成可以直接貼進 PHRASES 的格式，方便持續補齊
    need = {}
    for b in banks:
        for u in b["units"]:
            if not any(s["kind"] == "phrase" for s in u["steps"]):
                need.setdefault(b["id"], []).append((u["target"], u["id"]))
    nl = [f"units without a phrase step: {sum(len(v) for v in need.values())}",
          ""]
    for sid, items in need.items():
        nl.append(f'    "{sid}": [  # {len(items)}')
        nl.append("        " + ", ".join('"%s"' % t for t, _ in items))
        nl.append("    ],")
    (ROOT / "tools" / "need_phrase.txt").write_text("\n".join(nl), encoding="utf-8")
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(lines[0])


if __name__ == "__main__":
    main()